/**
 * Regenerates src/projects.config.ts from public/<id>/config.json files.
 * Run manually or via `npm start` (prestart hook).
 */
import fs from "fs";
import path from "path";
import { discoverProjects } from "./discover";

const OUT_FILE = path.resolve("./src/projects.config.ts");

const projects = discoverProjects();

const lines = [
  `// AUTO-GENERATED by scripts/sync-config.ts — do not edit directly.`,
  `// Add a public/<id>/config.json and run "npm run sync" to update.`,
  `import { ProjectConfig } from "./types/project";`,
  ``,
  `export const projects: ProjectConfig[] = ${JSON.stringify(projects, null, 2)};`,
  ``,
];

fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf-8");
console.log(`Synced ${projects.length} project(s) → src/projects.config.ts`);
