// AUTO-GENERATED by scripts/sync-config.ts — do not edit directly.
// Add a public/<id>/config.json and run "npm run sync" to update.
import { ProjectConfig } from "./types/project";

export const projects: ProjectConfig[] = [
  {
    "id": "scoutside",
    "name": "scoutside",
    "tagline": "College recruiting, finally clear.",
    "cta": "Your recruiting journey starts here.",
    "colors": {
      "bg": "#f5f1ec",
      "bgDark": "#1c1c1a",
      "accent": "#c9622d",
      "text": "#2a2a27",
      "textMuted": "#6b6b67"
    },
    "features": [
      {
        "title": "Your Recruiting Dashboard",
        "subtitle": "Personalized insights based on your profile, position, and graduation year.",
        "callout": "428 matched programs",
        "cardAlign": "left",
        "screenshot": "scoutside/screenshots/01-landing.png"
      },
      {
        "title": "Know Your Lane",
        "subtitle": "See exactly where your profile fits — and why — based on real NCAA data.",
        "callout": "Backed by historical NCAA data",
        "cardAlign": "right",
        "screenshot": "scoutside/screenshots/02-your-lane.png"
      },
      {
        "title": "Programs Where You Align",
        "subtitle": "Ranked by fit — not just division or geography.",
        "cardAlign": "left",
        "screenshot": "scoutside/screenshots/03-schools.png"
      },
      {
        "title": "Connect With Coaches",
        "subtitle": "AI-powered outreach that helps you draft emails, improve your tone, and follow up at the right time.",
        "callout": "AI-powered · Your data stays private",
        "cardAlign": "right",
        "screenshot": "scoutside/screenshots/04-outreach.png"
      }
    ]
  }
];
